### ISSUE TITLE
Node.js option

### ISSUE THREAD

**Issue by lozanoje** [phenomen/flc#14]
To specify different userdata folders to have several Foundry installations for testing.

Edit: and a checkbox to autoload localhost:port (the one specified at config.json of userdata) in flc when server starts

Edit 2: allow to add to favourites different configurations to different foundry versions (foundry directory) and userdata

This will help having different foundry versions with different userdata folders

**Comment by phenomen** [comment]
@lozanoje I added optional launch parameters in 3.0.0 (as well as your Spanish translation!).

FLC was never supposed to be some very advanced server management app, and the current Node launcher implementation is kinda barebones. I will experiment with tabs - it should also make the main screen less busy with stuff that players may not need.
