### ISSUE TITLE
Not selecting dedicated GPU on laptop

### ISSUE THREAD

**Issue by ian612** [phenomen/flc#16]
I'm using FLC on a laptop, and I've not been able to get the computer to use the dedicated Nvidia GPU in the laptop, it always defaults to the intel integrated graphics chip. This happens regardless of whether I try to force it to use the Nvidia chip with both Nvidia control panel and windows graphics settings.

I'm not sure if there's a way to build the exe such that windows recognizes it automatically as a "graphics heavy" application and uses dedicated graphics by default, but if so that'd be really useful.

Hardware:
i7-8550U, 16 GB DDR4 RAM
intel UHD Graphics 620
Nvidia MX150 2GB

**Comment by ian612** [comment]
As an addendum, if I disable the integrated graphics via device manager, foundry gives me a warning when I try and run it with FLC that my browser doesn't support hardware acceleration.

**Comment by VladGrant** [comment]
I am having the exact same issue. It's almost as if the executable isn't what the setting is bound to.

**Comment by ian612** [comment]
Oh interesting, now when I open my task manager (on a different PC), it's showing that there are a bunch of Microsoft Edge Webview2 processes underneath FLC... Maybe I need to force that application to use the GPU. Will try it out when I get home tonight

**Comment by ian612** [comment]
Managed to try it out, and it worked!!!
![image](https://github.com/phenomen/flc/assets/34078802/8384f11e-12d6-4dd0-85bd-da5bd0946b4b)

**Comment by phenomen** [comment]
@ian612 glad it worked!

**Comment by ian612** [comment]
Yeah, glad it’s working. If possible, it would be good to put this info in the readme or a help file within the application somewhere.

**Comment by VladGrant** [comment]
So is this considered resolved? I only ask because this is not the best solution for a couple of reasons.
1) Any program using edge webview will be using the GPU, not just FLC.
2) The folder name seems to be tied to a version, meaning it probably changes.

**Comment by phenomen** [comment]
> So is this considered resolved? I only ask because this is not the best solution for a couple of reasons.
> 
> 1. Any program using edge webview will be using the GPU, not just FLC.
> 2. The folder name seems to be tied to a version, meaning it probably changes.

Maybe in the future there will be a way to force GPU but for now there is no such API in the Tauri / WebView2.

I will add a checker for WebGL2 availability to the main window that will warn the user and provide steps to activate the dedicated GPU (if it exists).

**Comment by phenomen** [comment]
Added WebGL2 and GPU checked in the new build
![image](https://github.com/phenomen/flc/assets/138311/f5ffcd80-9cc7-47ef-a663-3e88212a2e36)
