### ISSUE TITLE
Feature Request : add the ability to run a limited list of plugins

### ISSUE THREAD

**Issue by franckflo** [phenomen/flc#20]
For GMs, if would be nice if FLC could allow a dev mode to install chrome plugins such as Beyond20, Rivet and other plugins that are used by GMs for prepare and run their games. I’m aware that this would go against the no-bloat principle of FLC, but it would be still be better then running out of Chrome of other browsers. Thanks !

**Comment by GabrielOsvair** [comment]
I think adding this feature makes it increasingly cumbersome and goes beyond the project's objective, which is to be simple and functional.

**Comment by franckflo** [comment]
That’s understandable.
