### ISSUE TITLE
Aliasing issue on SVGs and images

### ISSUE THREAD

**Issue by M0nk3yy** [phenomen/flc#22]
In a new DND5e world with no mods active.

Screenshot taken from FLC:

![image](https://github.com/phenomen/flc/assets/66137312/05f62355-3474-4d36-af38-a2eb537abd3e)

Screenshot taken from Firefox/Chrome:

![image](https://github.com/phenomen/flc/assets/66137312/86de3edb-818d-4ecd-9912-db644c8b7067)

As you can see the FLC image is more pixelated. This issue extends to other images too:

![image](https://github.com/phenomen/flc/assets/66137312/ae33e092-5105-4ab4-ae7a-15f0b76546b8)

I've seent his happen in the past and I think it was a Chromium issue? But I cannot reproduce this in Chrome or Firefox now. Seems to only occur in FLC.

**Comment by madereddy** [comment]
Can you try the latest build from: https://github.com/madereddy/flc?

**Comment by GabrielOsvair** [comment]
> Can you try the latest build from: https://github.com/madereddy/flc?

Will this repository no longer be updated?

**Comment by M0nk3yy** [comment]
> Can you try the latest build from: https://github.com/madereddy/flc?

Still seems to happen in the linked version of FLC but not my current versions of Chrome and Firefox.

**Comment by madereddy** [comment]
@GabrielOsvair Looks like Phenomen is working on a complete rewrite. I forked his repo and just updated the dependencies as I was having a bug in Chromium and upgrading it fixed it. 

https://github.com/phenomen/flc/issues/27

@M0nk3yy Can you try edge and see if the aliasing issue still exists?

**Comment by M0nk3yy** [comment]
> @M0nk3yy Can you try edge and see if the aliasing issue still exists?

I don't see any aliasing in Chrome, Firefox, or Edge. Only FLC.

**Comment by madereddy** [comment]
@M0nk3yy Do you have Zoomed Texture Antialiasing enabled in Foundry? Its in default game settings.

![image](https://github.com/phenomen/flc/assets/49539048/e14351a2-379d-4fb8-b8ae-19b4feaa1fe4)

I am unable to recreate the aliasing issue on the last couple builds from this repo: https://github.com/madereddy/flc

![image](https://github.com/phenomen/flc/assets/49539048/189e6b85-2d08-43e8-8c83-cf5a8b402e4c)

**Comment by M0nk3yy** [comment]
@madereddy You are right, this setting was off and since it is per-client I never noticed despite repeatedly connecting to the same world via different browsers. It does fix the issue, thank you for the tip.
