### ISSUE TITLE
Saved ip's bug

### ISSUE THREAD

**Issue by LupusVentus** [phenomen/flc#25]
Somehow I've saved bugged ip adress and now everytime I launch FLC I get empty screen and this error in console:
![image](https://github.com/phenomen/flc/assets/93127984/e22a49b6-0076-4aed-94a2-8df5f5324a42)
Would really like to know how to purge saved ip's. Reinstalling didn't help.

**Comment by LupusVentus** [comment]
Would really like to know how to purge saved ip's. Reinstalling didn't help.

**Comment by phenomen** [comment]
@LupusVentus sorry to hear that. In the upcoming complete code rewrite, I added a better protection / type checking.

For now, you may press F12, open Application tab, select Storage on the left and press Clear site data:

![image](https://github.com/phenomen/flc/assets/138311/fb565ebc-0456-423e-9e4d-f22eb1add8c9)

**Comment by LupusVentus** [comment]
Thanks, finally can use it again!
