### ISSUE TITLE
Dependabot Alerts Enabling

### ISSUE THREAD

**Issue by madereddy** [phenomen/flc#27]
Dependabot alerts should be enabled for this project along with basic CodeQL scanning. I forked this repo and enabled Dependabot and found PostCSS needed to be updated. Dependabot will automatically create PRs that can be merged without taking extra time. The PostCSS example below:

```
An issue was discovered in PostCSS before 8.4.31. It affects linters using PostCSS to parse external Cascading Style Sheets (CSS). There may be \r discrepancies, as demonstrated by @font-face{ font:(\r/*);} in a rule.
```

**Comment by phenomen** [comment]
@madereddy I'm working on a complete project rewrite and everything will be up-to-date.

**Comment by madereddy** [comment]
Created a simple dependabot PR: https://github.com/phenomen/flc/pull/31
