### ISSUE TITLE
AV Alert

### ISSUE THREAD

**Issue by brunocalado** [phenomen/flc#3]
Hi.

The AV is generating an alert:

![image](https://user-images.githubusercontent.com/4999783/229285148-b9c60920-2c32-494f-ac46-00f3f685226b.png)

**Comment by phenomen** [comment]
Here is a VirusTotal check for the latest version: https://www.virustotal.com/gui/file/219deb893f41bda79ebc9f7e835343867382935b6bf26c36a14aeb8ed9962949
