### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by dg1m** [phenomen/flc#38]
After 6+ hours of usage as a GM the memory usage will be at 8GB or more and FLC slows way down. If this is inherent of webview2 or Foundry then close this issue.

**Comment by phenomen** [comment]
Do you use server launcher or just a client part?

**Comment by dg1m** [comment]
I should say my Foundry Client slows way down. The players are unaffected. Closing FLC frees up the memory and then I can reopen FLC, connect to my server, and continue the game.

**Comment by phenomen** [comment]
Fixed in FLC 6.0
