### ISSUE TITLE
Pathfinder 2e rendering issues on macOS

### ISSUE THREAD

**Issue by johncarney** [phenomen/flc#44]
I'm seeing rendering issues in Pathfinder 2e game worlds on macOS. See screenshots below.

# FLC

![image](https://github.com/phenomen/flc/assets/322950/9c16539a-e747-4275-8149-cb7d6c4e8937)
![image](https://github.com/phenomen/flc/assets/322950/9b5c48b8-0288-4a89-8467-aa9004c288da)

# Firefox

<img width="714" alt="image" src="https://github.com/phenomen/flc/assets/322950/5371b1fe-8e0a-428d-9603-7f27f5ac8906">
<img width="505" alt="image" src="https://github.com/phenomen/flc/assets/322950/daecd762-197e-45bd-87a5-f0a6b7206643">

# Chrome

<img width="723" alt="image" src="https://github.com/phenomen/flc/assets/322950/41622a72-292e-4dab-a70c-d386fd19fe2c">
<img width="505" alt="image" src="https://github.com/phenomen/flc/assets/322950/dd7b2bc0-da52-4ccc-9b7a-ef8aea6b5ebd">

**Comment by phenomen** [comment]
macOS uses Webkit instead of Webview (Chromium) and those rendering issues are outside of something that I may fix.
Modern macOS  / Webkit versions have much better compatibility with web standarts so you may try to update your OS.
Also, FLC is now available for macOS ARM (M1+).
