### ISSUE TITLE
Launching and joining a server results in 2 windows

### ISSUE THREAD

**Issue by M0nk3yy** [phenomen/flc#47]
The previous version could launch and join a server in a single window, which was tidy and convenient for my use.

V6.0.0 always joins the server in a separate window. This seems unnecessary, since there is little else I can do with that window other than stop the server. Now if I want to launch and join 2 servers at once, I need 4 windows running. (Similar to if I had manually run the node servers via command prompt).

I am sure this change was deliberate, but wanted to register my feedback. If there is some Windows setting, or command line argument that I can use that would mean a separate window isn't used, that would be good too.

**Comment by phenomen** [comment]
Opening a separate window for Foundry is necesarry for Zoom and Fullscreen to work since those commands are "transfered" from the main window. I may add an ability to open multiple Foundry windows if there is a need for it.
