### ISSUE TITLE
CtRL + F11 fullscreen no longer working

### ISSUE THREAD

**Issue by esotericamod** [phenomen/flc#48]
im not sure if the hotkey is different now but it doesnt seem to work anymore

**Comment by phenomen** [comment]
Added global hotkeys back. `Ctrl`+`F11` should work again, as well as `Ctrl`+`+`, `Ctrl`+`-` and `Ctrl`+`0`.

Please install FLC 6.2.0 manually as auto-updater was not working properly in the previous version.
https://github.com/phenomen/flc/releases

**Comment by esotericamod** [comment]
it still doesnt work. CTRL + 0 CTRL + - and CTRL+ 0 all work, just not CTRL+ F11. Now there is also no fullscreen button on 6.3.0 so i cant use that workaround anymore

**Comment by phenomen** [comment]
> it still doesnt work. CTRL + 0 CTRL + - and CTRL+ 0 all work, just not CTRL+ F11. Now there is also no fullscreen button on 6.3.0 so i cant use that workaround anymore

Try to click to the main window, then click on Foundry window and try the hotkey again. I think I know what's up and will fix it in the next release.

**Comment by phenomen** [comment]
`Ctrl+F11` should work consistently in 6.4.0.
