### ISSUE TITLE
Add to README foreign Youtubers

### ISSUE THREAD

**Issue by brunocalado** [phenomen/flc#6]
Hi.

I made a video about flc for the brazilian community. It's in portuguese. What do you think about add a link for this in the readme? Also, when more youtubers make videos you can add to this foreign section.

https://youtu.be/brGlqFXqwrU

tks

**Comment by phenomen** [comment]
@brunocalado Thanks! Yes, I need to add a proper Readme on Github. Once it's done, I will link this video in the instructions.

Also, I would like to add pt-BR language. There are not that many strings and if someone can help me translate it to Portuguese, it would be great https://github.com/phenomen/flc/blob/main/src/lib/data/i18n.json

**Comment by brunocalado** [comment]
> @brunocalado Thanks! Yes, I need to add a proper Readme on Github. Once it's done, I will link this video in the instructions.
> 
> Also, I would like to add pt-BR language. There are not that many strings and if someone can help me translate it to Portuguese, it would be great https://github.com/phenomen/flc/blob/main/src/lib/data/i18n.json

I sent the ptbr
