### ISSUE TITLE
HUD Scale

### ISSUE THREAD

**Issue by brunocalado** [phenomen/flc#9]
Hi.

Can you add the possiblity to scale the HUD? Like a regular browser.

tks

**Comment by dsakura** [comment]
Same here! I'm waiting for this resource to start using this client, for now I use another client, as it is necessary for me. Thx

**Comment by cs96and** [comment]
Shameless plug for my UI Scaler module...
https://foundryvtt.com/packages/uiscaler

**Comment by lucaspicerni** [comment]
I third this!

**Comment by phenomen** [comment]
Unfortunately, it's not currently possible due to limitation in tauri/wry 
https://github.com/tauri-apps/tauri/issues/3310

I'm keeping eye on it and will implement zoom as soon as possible.

**Comment by lucaspicerni** [comment]
Hello! I believe this limitation has been resolved in tauri/wry and can be changed in FLC, no?

**Comment by phenomen** [comment]
Fixed in FLC 6.0
